server:
  port: 7101
eureka:
  #  instance:
  #    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  #    prefer-ip-address: true
  #    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://euk1.com:7001/eureka/,http://euk2.com:7002/eureka/
    #拉取服务注册信息，默认30秒
    registry-fetch-interval-seconds: 5
    #开启健康检查（用于上报节点信息，需要spring-boot-starter-actuator依赖）
    healthcheck:
      enabled: true
  instance:
    #持续发送间隔默认30秒，心跳间隔（租期更新时间间隔）
    lease-renewal-interval-in-seconds: 5
    #续约到期时间 默认90秒（租期到期时间）
    lease-expiration-duration-in-seconds: 60
    #自定义信息
    metadata-map:
      user: zc
spring:
  application:
    name: sc-eureka-provider
