ribbon:
  # 连接超时(ms)
  ConnectTimeout: 1000
  # 业务逻辑超时(ms)
  ReadTimeout: 6000
  # 同一台实例最大重试次数，不包括首次调用
  MaxAutoRetries: 3
  # 重试负载均衡其他实例最大重试次数，不包括首次调用
  MaxAutoRetriesNextServer: 3
  # 是否所有操作都重试
  OkToRetryOnAllOperations: false
# 启用 hystrix 熔断机制
feign:
  hystrix:
    enabled: true
# hystrix 默认超时1s
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          # 方法一: 线程池
          thread:
            timeoutInMilliseconds: 60000
          # 方法二: 或者信号量
#          strategy: SEMAPHORE
      # 设置熔断器失败的个数，默认为20个，这里我给了100个，只有超过100个才会发生短路
      circuitBreaker:
        requestVolumeThreshold: 100
    # fallback 线程数量
    fallBack:
      isolation:
        semaphone:
          maxConcurrentRequests: 50
  # feign 线程池大小 默认为10
  threadpool:
    default:
      coreSize: 100
  # 高版本Springboot 代理流允许列表放开（否则无法使用熔断器监控可视化页面http://localhost:7501/hystrix）
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoints:
    web:
      exposure:
        # 开启所有端点
        include: "*"
  endpoint:
    health:
      # 显示所有细节
      show-details: always
      enabled: true